@token = replace_with_jwt

POST http://localhost:3000/api/auth
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "replace_with_password"
}

###

POST http://localhost:3000/api/auth
Content-Type: application/json

{
    "email": "user@example.com",
    "password": "replace_with_password"
}

###

GET http://localhost:3000/api/auth/tiempo
Authorization: Bearer {{token}}

###

GET http://localhost:3000/api/roles
Authorization: Bearer {{token}}
