@token = replace_with_admin_jwt

POST http://localhost:3000/api/auth
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "replace_with_password"
}

###

POST http://localhost:3000/api/usuarios/registro
Content-Type: application/json

{
    "nombre": "Cliente de prueba",
    "email": "cliente@example.com",
    "password": "PasswordSegura123!"
}

###

GET http://localhost:3000/api/usuarios
Authorization: Bearer {{token}}

###

POST http://localhost:3000/api/usuarios
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nombre": "Administrador de prueba",
    "email": "admin2@example.com",
    "password": "PasswordSegura123!",
    "rol": "Administrador"
}

###

PUT http://localhost:3000/api/usuarios/cliente@example.com
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nombre": "Cliente actualizado",
    "email": "cliente@example.com",
    "rol": "Usuario"
}

###

DELETE http://localhost:3000/api/usuarios/cliente@example.com
Authorization: Bearer {{token}}
